name: 'Gateway Tests'
description: 'Tests that gateway features work'
runs:
  using: 'composite'
  steps:
    - name: Test health check endpoint
      run: |
        response=$(curl --silent http://localhost:8080/healthcheck)
        if [[ "$response" != "Healthy" ]]; then
          echo "Test 1 failed: Expected 'Healthy' but got '$response'"
          exit 1
        else
          echo "Gateway Healthcheck passed"
        fi
      shell: bash

    - name: Test add datafile endpoint
      run: |
        # upload first file
        response=$(curl --silent -X POST \
                          -F "file=@testdata/binding/abl/7n9g.pdb;filename=7n9g.pdb" \
                          -F "filename=7n9g.pdb" \
                          -F "wallet_address=0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" \
                          http://localhost:8080/datafiles)
        if echo "$response" | jq -e '.cid' > /dev/null; then
          echo "File upload test passed"
        else
          echo "File upload test failed: 'cid' key not found in the response"
          exit 1
        fi

        # upload second file
        response=$(curl --silent -X POST \
                          -F "file=@testdata/binding/abl/ZINC000003986735.sdf;filename=ZINC000003986735.sdf" \
                          -F "filename=ZINC000003986735.sdf" \
                          -F "wallet_address=0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" \
                          http://localhost:8080/datafiles)
        if echo "$response" | jq -e '.cid' > /dev/null; then
          echo "File upload test passed"
        else
          echo "File upload test failed: 'cid' key not found in the response"
          exit 1
        fi
      shell: bash

    - name: Set Tool JSON content
      id: tooljson-setter
      run: echo "TOOL_JSON=$(cat tools/equibind.json | jq -c .)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Test add Tool Endpoint
      run: |
        response=$(curl -s -X POST "http://localhost:8080/tools" \
               -H "Content-Type: application/json" \
               -d "{
                   \"toolJson\": \"${{ steps.tooljson-setter.outputs.TOOL_JSON }}\",
                   \"walletAddress\": \"0xab5801a7d398351b8be11c439e05c5b3259aec9b\"
                 }")

        cid_value=$(echo "$response" | jq -r '.cid')

        if [ "$cid_value" == "QmTFMb527A3VDCmVNwC1d6yCM3eUdvLwHsEXwtRULeczZ2" ]; then
           echo "Add Tool upload test passed"
        else
           echo "Add Tool upload test failed: Expected 'QmTFMb527A3VDCmVNwC1d6yCM3eUdvLwHsEXwtRULeczZ2' but got '$cid_value'"
           exit 1
        fi
      shell: bash
