---

version: "3.7"

services:
  requester:
    image: "ghcr.io/bacalhau-project/bacalhau:v${BACALHAU_VERSION:-1.1.2}"
    hostname: requester
    command: serve --ipfs-connect '/dns4/ipfs/tcp/5001' --node-type requester --private-internal-ipfs=false --peer none --labels "owner=labdao" --job-selection-probe-http "http://receptor:8080/judge"
    environment:
      # BACALHAU_ENVIRONMENT: production
      LOG_LEVEL: trace
    networks:
      plex:
    ports:
      - 1234:1234
      - 1235:1235
    depends_on:
      ipfs:
        condition: service_healthy

  # sidecar container for requester healthcheck
  requester_health:
    image: "alpine"
    command: sh -c 'apk add curl && sleep infinity'
    depends_on:
      requester:
        condition: service_started
    healthcheck:
      test: curl -f http://requester:1234/api/v1/healthz
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      plex:

  compute:
    image: "ghcr.io/bacalhau-project/bacalhau:v${BACALHAU_VERSION:-1.1.2}"
    hostname: compute
    user: root
    command: serve --ipfs-connect '/dns4/ipfs/tcp/5001' --node-type compute --labels "owner=labdao" --private-internal-ipfs=false --peer "/dns4/requester/tcp/1234/http" --job-selection-probe-http "http://receptor:8080/judge" --max-job-execution-timeout "24h" --job-selection-accept-networked --job-selection-data-locality anywhere --port 2234 --swarm-port 2235 --host 172.16.238.200
    environment:
      LOG_LEVEL: trace
      DOCKER_DEFAULT_PLATFORM: linux/amd64
      # Keep containers around - I think
      KEEP_STACK: "true"
      BACALHAU_DIR: /tmp/bacalhau
      BACALHAU_PREFERRED_ADDRESS: "172.16.238.200"
    ports:
      - 2234:2234
      - 2235:2235
    networks:
      plex:
        ipv4_address: 172.16.238.200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      ipfs:
        condition: service_healthy
      requester:
        condition: service_started
      requester_health:
        condition: service_healthy

  # sidecar container for compute healthcheck
  compute_health:
    image: "alpine"
    command: sh -c 'apk add curl && sleep infinity'
    depends_on:
      compute:
        condition: service_started
    networks:
      plex:
    healthcheck:
      test: curl -f http://compute:2234/api/v1/healthz
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  dbbackend:
    image: "postgres:15.4"
    environment:
      POSTGRES_PASSWORD: labdao
      POSTGRES_USER: labdao
      POSTGRES_DB: backend
    ports:
      - 5432:5432
    networks:
      plex:
    volumes:
      - dbdata-backend:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres  || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: .
      cache_from:
        - quay.io/labdao/backend:latest
      args:
        BACALHAU_VERSION: ${BACALHAU_VERSION:-1.1.2}
    ports:
      - 8080:8080
    networks:
      plex:
    environment:
      POSTGRES_PASSWORD: labdao
      POSTGRES_USER: labdao
      POSTGRES_DB: backend
      POSTGRES_HOST: dbbackend
      BACALHAU_API_HOST: requester
      IPFS_API_HOST: ipfs
      FRONTEND_URL: http://localhost:3000
    depends_on:
      dbbackend:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthcheck || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/frontend:latest
      args:
        NEXT_PUBLIC_PRIVY_APP_ID: ${NEXT_PUBLIC_PRIVY_APP_ID:-clo7adk6w07q7jq0f08yrnkur}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8080}
        NEXT_PUBLIC_IPFS_GATEWAY_ENDPOINT: ${NEXT_PUBLIC_IPFS_GATEWAY_ENDPOINT:-http://localhost:8888/ipfs/}
    environment:
      NODE_ENV: 'production'
    ports:
      - 3000:3000
    networks:
      plex:

  dbreceptor:
    image: "postgres:15.4"
    environment:
      POSTGRES_PASSWORD: labdao
      POSTGRES_USER: labdao
      POSTGRES_DB: receptor
    volumes:
      - dbdata-receptor:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres  || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      plex:

  receptor:
    build:
      context: ./receptor
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/receptor:latest
    environment:
      PGHOST: dbreceptor
      PGUSER: labdao
      PGPASSWORD: labdao
      PGDATABASE: receptor
      PGSSLMODE: disable
    depends_on:
      dbreceptor:
        condition: service_healthy
    networks:
      plex:

  ipfs:
    hostname: ipfs
    build:
      context: ./docker/images/ipfs
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/ipfs:latest
    volumes:
      - ipfs:/data/ipfs
    environment:
      IPFS_LOGGING: "debug"
      IPFS_GATEWAY_PORT: "8888"
      IPFS_DEBUG: "true"
    ports:
      - 4001:4001
      - 5001:5001
      - 8888:8888
    networks:
      plex:

volumes:
  dbdata-backend:
  dbdata-receptor:
  ipfs:


networks:
  plex:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
