# Minimal compose for private setup
# To bring up network in private mode use:
# docker-compose  -f docker-compose.yml -f docker-compose-private.yml up -d

---

services:
  ipfs:
    image: private_ipfs
    build:
      context: ./docker/images/ipfs
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/ipfs:latest
      args:
        IPFS_S3_ENABLED: "false"
    environment:
      IPFS_S3_ENABLED: "false"
      IPFS_SWARM_KEY_BASE64: "L2tleS9zd2FybS9wc2svMS4wLjAvCi9iYXNlMTYvCjk0Y2Y4ODFiMDZmZDI5YTgxNDVlMmY2MjNiMmRjNGMwNTU2Y2QxNTIwNWM4YjhjMzg0YWEzOThkY2U4YWFhMzYK"
      PRIVATE_IPFS: "true"
      LIBP2P_FORCE_PNET: "1"
      IPFS_DEBUG: "true"
    volumes:
      - privateipfs:/data/ipfs

volumes:
  privateipfs:
