# CI specific overrides
---

version: "3.7"

services:
  compute:
    user: "1001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /home/runner/.bacalhau/executor_storages/:/home/runner/.bacalhau/executor_storages/
