# CI specific overrides
---

version: "3.7"

services:
  compute:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /root/.bacalhau/executor_storages/:/root/.bacalhau/executor_storages/
