---

services:
  # sidecar container for setting up required key material
  requester-setup:
    image: "public.ecr.aws/docker/library/alpine:latest"
    command: >
      sh -c '
      mkdir -p /home/nonroot/.bacalhau &&
      echo CAASqAkwggSkAgEAAoIBAQDQubr6zD3DLEQ07K2wPUQEFfVQLfqTQihc8lQOWuihElXcqZJLajK4od5zc+nCQ/jyUmrmOsYd7aKBmXfyTwOBwCaXEpqqxlP+Pal/Ruh+Ptpfl11KP4sHg3P5sYM/bMRJrEtg1k3mbaToioH5I9GrH7zv5LDHUSezbYFCJ4ZyakUgal+GXPx+TpbdhIx93pZXPHzxgd/m1rbSyiR7sUqXAokzKf2Qv1sOnGrHHcKy8DiSrXo+YUyDRC3lQKwaSfyrBFq1BLqE+E383zYIc5yhcV3kSGivQ2v9o67jEbss3f3ogEfXplsAnBh1S+RfcfneUaRs/UC/+8kyWAC0sU1ZAgMBAAECggEAHZZWZPrSvnnl6UKrlFH69EFQlt8NqBY2toY7WBWW6E47EZ6P+FTDf9yiNed2eW09OsxoDt7B+rgW0xw4HocIzjm4vq2Kcy7N9To0brBUgKDUP7yrIr1DLft6UyjQnAsFABSGUuHOBR4BxFzt860aKZHELJVUYcylPhAFxKTpsAoSy68/Zfkz5wjGtC/ImcHIwGub7NKNmbouQQe6p4beOkYmyVsX6RL/7RPMi7Jvspq0nj0V0j/T13XBUH4b862cqs54HuJQjI9j4QijA9SuCySXQfJw2If8sM7z/3w+IwYhp2JIu4oMTIppCvTBgzAmh+7OMqfOlL7av9iMmqQiAQKBgQDyDtX4TxN1JiFdJg8L3AV8e53GE2eAGY7zpiN7CDrACDXeyrni8fIVz4wY5Pf7+E49dI1S67dsyHVb2dK6Gg4tyECXoRHYPMRktw8LJf9QfCfYsGrpoj/yq2UZ5SqU1Uh70h3b7W3vdZXPZO1BBzT2iwTPGQl/0I0bunSTl72gYQKBgQDcv2etOyDp72NaiZduLpia0RVc92MAZLyoWyq4rscfjU0MvkCPyTa6sKjF2uaUDS5R8yVHB/6+2Mzs4LuWWpNtp6b3rG88CXxfbGDIYn2BOXDqQ9s2/ceISkNMq+NbfcUbbNvG920Ot20VKjkl9s7LcEC0cLiVU14oWd8BOV6v+QKBgQDWOk8g7ktYOSD6Ib7bTiUE4RrnvTCy7OvZs8ZfEw97+UhEH8OYmW0Z5JAnUC4xsLb+KPMS2k+CVX+YhRW9Y2X9GugfyovShyWBxYno4f4uq1NQsgJNOC3EhfB6lJm1E3aNL48BoAbWEYk+/iIElW5IbQ0ahRwlJNxeGA0ouvk2wQKBgQDZYfwdEa9V8BItJHXlYSmSu/eHt27dAlbui+jEOgmJPsLzm59EeWfV7QYm4WxTu68zsHezPWJWWnVjh+PzKnsobwLzv/FCdCzwY2/jpWnmicRyTiRgQQXvZwJjTJn2jSI/4bGEfD//UA6x2wSwKB55JK/zgVWkZ5a/sdD0CaT/MQKBgA7CMHQIjXl8FqATmBgiejGV6BnbUHko4m0Ab7fQUZY1qlgKrqcXgFmMQkb+p8Og1YeVn8Qy8xuvueAfwemA8OxvLuQNzQcA2qhGZID4Tu2Ng+XIkNxMj1gJelppqVeDnZSFr3TbZcSXIVhk1idAnpGDilS8cOO6LUY/hH/IVGGe > /home/nonroot/.bacalhau/private_key.1235 &&
      chown -R 65532:65532 /home/nonroot/'
    volumes:
      - requestervolume:/home/nonroot/

  requester:
    image: "ghcr.io/bacalhau-project/bacalhau:${BACALHAU_VERSION:-v1.1.2}"
    hostname: requester
    command: serve --ipfs-connect '/dns4/ipfs/tcp/5001' --node-type requester --private-internal-ipfs=false --peer none
    volumes:
      - requestervolume:/home/nonroot/
    environment:
      # BACALHAU_ENVIRONMENT: production
      # LOG_LEVEL: trace
      LOG_LEVEL: info
    ports:
      - 1234:1234
      - 1235:1235
    depends_on:
      ipfs:
        condition: service_healthy
      requester-setup:
        condition: service_completed_successfully

  # sidecar container for requester healthcheck
  requester-health:
    image: "public.ecr.aws/docker/library/alpine:latest"
    command: sh -c 'apk add curl && sleep infinity'
    depends_on:
      requester:
        condition: service_started
    healthcheck:
      test: curl -f http://requester:1234/readyz
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10s

  compute:
    image: "ghcr.io/bacalhau-project/bacalhau:${BACALHAU_VERSION:-v1.1.2}"
    hostname: compute
    user: root
    command: serve --ipfs-connect '/dns4/ipfs/tcp/5001' --node-type compute --labels "owner=labdao" --private-internal-ipfs=false --peer "/dns4/requester/tcp/1235/p2p/Qmd2oBsjjvtUYRmb7zhDEPhSf9YbxA1a7ZLZ6hyCwMqpnh"
    environment:
      # LOG_LEVEL: trace
      LOG_LEVEL: info
      DOCKER_DEFAULT_PLATFORM: linux/amd64
      BACALHAU_SERVE_IPFS_PATH: /tmp/lilypad/data/ipfs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    depends_on:
      ipfs:
        condition: service_healthy
      requester:
        condition: service_started
      requester-health:
        condition: service_healthy

  # sidecar container for compute healthcheck
  compute-health:
    image: "public.ecr.aws/docker/library/alpine:latest"
    command: sh -c 'apk add curl && sleep infinity'
    depends_on:
      compute:
        condition: service_started
    healthcheck:
      test: curl -f http://compute:1234/readyz
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10s

  # geth
  geth:
    image: "ethereum/client-go"
    hostname: geth
    command: --datadir /data/geth --dev --ws --ws.api web3,eth,net --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins '*' --http --http.api web3,eth,net --http.addr 0.0.0.0 --http.corsdomain '*' --http.port 8545 --http.vhosts '*' --graphql
      # environment:
      # BACALHAU_ENVIRONMENT: production
      # LOG_LEVEL: trace
    volumes:
      - geth:/data/geth
    ports:
      - 8545:8545
      - 8546:8546
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8545 || exit 1
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10s

  # lilypad-setup
  lilypad-setup:
    image: "public.ecr.aws/docker/library/node:20"
    command: >
      sh -x -c '

      if [ -f /app/lilypad/done ]; then exit;fi &&

      apt-get -q update && apt-get -q -y install sudo &&

      rm -rf /tmp/lilypad/lilypad /tmp/geth &&

      wget --no-verbose https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-${GETH_VERSION:-1.13.5-916d6a44}.tar.gz -O geth.tgz &&
      tar -zxvf geth.tgz &&
      mv geth-linux-amd64-${GETH_VERSION:-1.13.5-916d6a44}/geth /usr/local/bin/ &&

      mkdir -p /tmp/lilypad/data &&
      chmod -R 777 /tmp/lilypad/data &&

      cd /tmp/lilypad/ &&
      git clone https://github.com/bacalhau-project/lilypad --branch ${LILYPAD_VERSION:-v2.0.0-e5c38d5} &&
      cd lilypad &&

      sed -i "s/localhost/geth/g" hardhat/hardhat.config.ts &&
      (cd hardhat && yarn install) &&
      ./stack print-env > .env &&

      echo "export WEB3_RPC_URL=ws://geth:8546" >> .env &&
      echo "export LOG_LEVEL=info" >> .env &&
      echo "export WEB3_CONTROLLER_ADDRESS=0x59b670e9fA9D0A427751Af201D676719a970857b" >> .env &&
      echo "export BACALHAU_API_HOST=requester" >> .env &&

      cp -rav .env /app/lilypad/.env &&
      . ./.env &&

      /usr/local/bin/geth --exec "eth.sendTransaction({from: eth.coinbase, to: \"$${ADMIN_ADDRESS}\", value: new web3.BigNumber(eth.getBalance(eth.coinbase)).minus(web3.toWei(1, \"ether\"))  })" attach "http://geth:8545" &&
      bash -x ./stack fund-services-ether &&
      bash -x ./stack deploy &&
      bash -x ./stack fund-services-tokens &&
      bash -x ./stack balances &&
      touch /app/lilypad/done &&

      cp -rav /app/lilypad/.env /app/solver/.env &&
      echo export WEB3_PRIVATE_KEY=$$SOLVER_PRIVATE_KEY >> /app/solver/.env &&
      echo export JOB_CREATOR_ADDRESS=$$JOB_CREATOR_ADDRESS >> /app/solver/.env &&
      echo export SERVICE_MEDIATORS=$$MEDIATOR_ADDRESS >> /app/solver/.env &&

      cp -rav /app/lilypad/.env /app/mediator/.env &&
      echo export WEB3_PRIVATE_KEY=$$MEDIATOR_PRIVATE_KEY >> /app/mediator/.env &&
      echo export WEB3_DIRECTORY_ADDRESS=$$DIRECTORY_ADDRESS >> /app/mediator/.env &&
      echo export SERVICE_SOLVER=$$SOLVER_ADDRESS >> /app/mediator/.env &&

      cp -rav /app/lilypad/.env /app/resource-provider/.env &&
      echo export WEB3_PRIVATE_KEY=$$RESOURCE_PROVIDER_PRIVATE_KEY  >> /app/resource-provider/.env &&
      echo export SERVICE_SOLVER=$$SOLVER_ADDRESS  >> /app/resource-provider/.env &&
      echo export SERVICE_MEDIATORS=$$MEDIATOR_ADDRESS  >> /app/resource-provider/.env &&

      cp -rav /app/lilypad/.env /app/jobcreator/.env &&
      echo export WEB3_PRIVATE_KEY=$$SOLVER_PRIVATE_KEY >> /app/jobcreator/.env &&
      echo export SERVICE_SOLVER=$$SOLVER_ADDRESS >> /app/jobcreator/.env &&
      echo export SERVICE_MEDIATORS=$$MEDIATOR_ADDRESS >> /app/jobcreator/.env

      echo export SERVICE_SOLVER=$${SOLVER_ADDRESS} >> .env &&
      echo export SERVICE_MEDIATORS=$${MEDIATOR_ADDRESS} >> .env &&
      echo export WEB3_PRIVATE_KEY=$${ADMIN_PRIVATE_KEY} >> .env &&
      echo export WEB3_RPC_URL=ws://localhost:8546 >> .env'

    environment:
      USER: root
    volumes:
      - lilypad:/app/lilypad
      - solver:/app/solver
      - mediator:/app/mediator
      - resource-provider:/app/resource-provider
      - jobcreator:/app/jobcreator
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/lilypad:/tmp/lilypad
    depends_on:
      geth:
        condition: service_healthy

  # solver
  lilypad-solver:
    build:
      context: ./docker/images/lilypad
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/lilypad:pr-802
      args:
        LILYPAD_VERSION: ${LILYPAD_VERSION:-v2.0.0-e5c38d5}
        BACALHAU_VERSION: ${BACALHAU_VERSION:-v1.1.2}
    hostname: lilypad-solver
    command: solver
    environment:
      SERVER_PORT: 8080
      SERVER_URL: http://lilypad-solver:8080
    ports:
      - 8080:8080
    volumes:
      - solver:/app/lilypad
    depends_on:
      geth:
        condition: service_healthy
      lilypad-setup:
        condition: service_completed_successfully

  # mediator
  lilypad-mediator:
    build:
      context: ./docker/images/lilypad
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/lilypad:pr-802
      args:
        LILYPAD_VERSION: ${LILYPAD_VERSION:-v2.0.0-e5c38d5}
        BACALHAU_VERSION: ${BACALHAU_VERSION:-v1.1.2}
    hostname: lilypad-mediator
    command: mediator
    volumes:
      - mediator:/app/lilypad
    depends_on:
      geth:
        condition: service_healthy
      lilypad-setup:
        condition: service_completed_successfully
      lilypad-solver:
        condition: service_started

  # resource-provider
  lilypad-resource-provider:
    build:
      context: ./docker/images/lilypad
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/lilypad:pr-802
      args:
        LILYPAD_VERSION: ${LILYPAD_VERSION:-v2.0.0-e5c38d5}
        BACALHAU_VERSION: ${BACALHAU_VERSION:-v1.1.2}
    hostname: lilypad-resource-provider
    command: resource-provider
    volumes:
      - resource-provider:/app/lilypad
      - /tmp/lilypad:/tmp/lilypad
    depends_on:
      geth:
        condition: service_healthy
      lilypad-solver:
        condition: service_started
      lilypad-mediator:
        condition: service_started
      lilypad-setup:
        condition: service_completed_successfully
      requester-health:
        condition: service_healthy
      compute-health:
        condition: service_healthy

  # jobcreator
  lilypad-jobcreator:
    build:
      context: ./docker/images/lilypad
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/lilypad:pr-802
      args:
        LILYPAD_VERSION: ${LILYPAD_VERSION:-v2.0.0-e5c38d5}
        BACALHAU_VERSION: ${BACALHAU_VERSION:-v1.1.2}
    hostname: lilypad-jobcreator
    command: jobcreator
    volumes:
      - jobcreator:/app/lilypad
    depends_on:
      geth:
        condition: service_healthy
      lilypad-solver:
        condition: service_started
      lilypad-mediator:
        condition: service_started
      lilypad-resource-provider:
        condition: service_started
      lilypad-setup:
        condition: service_completed_successfully

  ipfs:
    hostname: ipfs
    build:
      context: ./docker/images/ipfs
      dockerfile: ./Dockerfile
      cache_from:
        - quay.io/labdao/ipfs:latest
    volumes:
      - ipfs:/data/ipfs
    environment:
      IPFS_GATEWAY_PORT: "8888"
    ports:
      - 4001:4001
      - 5001:5001
      - 8888:8888

volumes:
  dbdata-backend:
  ipfs:
  lilypad:
  solver:
  mediator:
  jobcreator:
  resource-provider:
  requestervolume:
  geth:
