apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ipfs
  name: ipfs
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: ipfs
