- name: "Gather service facts"
  ansible.builtin.service_facts:

- name: "Disable unattended upgrades service"
  ansible.builtin.systemd:
    name: "unattended-upgrades.service"
    enabled: false
    masked: true
    state: "stopped"
  when: ansible_facts.services["unattended-upgrades.service"] is defined

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - aptitude
      - ca-certificates
      - curl
      - git
      - gnupg
      - gzip
      - lsb-release
      - pip
      - tar
      - unzip
      - jq
      - tree
      - net-tools

- name: Install required pip packages
  become: true
  ansible.builtin.pip:
    name:
      - boto3
