- name: "Remove unattended upgrades"
  become: true
  ansible.builtin.package:
    name: "unattended-upgrades"
    state: absent

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - aptitude
      - ca-certificates
      - curl
      - git
      - gnupg
      - gzip
      - lsb-release
      - pip
      - tar
      - unzip
      - jq
      - tree
      - net-tools

- name: Install required pip packages
  become: true
  ansible.builtin.pip:
    name:
      - pip
      - boto3
      - pyopenssl
