- name: "Gather service facts"
  become: true
  ansible.builtin.service_facts:

- name: "Disable unattended upgrades service"
  become: true
  ansible.builtin.systemd:
    name: "unattended-upgrades.service"
    enabled: false
    masked: true
    state: "stopped"
  when: ansible_facts.services["unattended-upgrades.service"] is defined

- name: "Remove unattended upgrades"
  become: true
  ansible.builtin.package:
    name: "unattended-upgrades"
    state: absent

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - aptitude
      - ca-certificates
      - curl
      - git
      - gnupg
      - gzip
      - lsb-release
      - pip
      - tar
      - unzip
      - jq
      - tree
      - net-tools

        # - name: Install required pip packages
        #   become: true
        #   ansible.builtin.pip:
        #     name:
        #       - pip
        #       - boto3
        #       - pyopenssl
        #      extra_args: --break-system-packages
        #

- name: allow ipv4 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: allow ipv6 forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Enable UFW
  become: true
  community.general.ufw:
    state: enabled

- name: Open ssh port
  become: true
  community.general.ufw:
    rule: allow
    state: reloaded
    port: "22"
    proto: "tcp"

- name: deny other incoming
  become: true
  community.general.ufw:
    rule: deny
    direction: "incoming"
