---
# Docker
- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Create the docker group
  become: true
  ansible.builtin.group:
    name: docker

- name: Add ubuntu user to docker group
  become: true
  ansible.builtin.user:
    name: ubuntu
    groups: docker

- name: Install docker
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true

- name: Define base docker config
  ansible.builtin.set_fact:
    docker_base_config:
      live-restore: true
      max-concurrent-downloads: 20
      max-download-attempts: 5
      storage-driver: overlay2
    docker_custom_config: {}

- name: Update Docker custom config for GPU nodes
  ansible.builtin.set_fact:
    docker_custom_config:
      runtimes:
        nvidia:
          path: "/usr/bin/nvidia-container-runtime"
          runtimeArgs: []
  when: num_of_gpus is defined and num_of_gpus | int > 0

- name: Push custom docker daemon config
  become: true
  ansible.builtin.copy:
    content: "{{ docker_base_config | combine(docker_custom_config) | to_json(indent=2, sort_keys=True) }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0400"
  notify: Restart docker
