# Nvidia
- name: Add Nvidia Keyring
  become: true
  ansible.builtin.apt:
    deb: https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_distribution }}/x86_64/cuda-keyring_1.1-1_all.deb

- name: Get Nvidia Container Tookit GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey

- name: Add Nvidia Container Tookit Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /
    state: present

- name: Install nvidia toolkit
  become: true
  ansible.builtin.apt:
    pkg: nvidia-container-toolkit
    update_cache: true

- name: Ensure Nvidia persitence daemon is started
  ansible.builtin.systemd:
    name: nvidia-persistenced

- name: Enable debug by uncommenting debug line in nvidia container runtime config
  ansible.builtin.replace:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: '^\s*#*\s*(debug.*)'
    replace: '\1'
  notify:
    - Restart docker

