---
- name: Create unix group
  become: true
  ansible.builtin.group:
    name: "{{ item.team }}"

- name: Create the shared folder
  become: true
  ansible.builtin.file:
    path: /srv/data/teams/{{ item.team }}
    state: directory
    owner: root
    group: "{{ item.team }}"
    mode: "2775"

# This is required to set the right permissions in the checkpoints folder for the shared team directory
- name: Create the checkpoint folder in the shared team folder.
  become: true
  ansible.builtin.file:
    path: /srv/data/teams/{{ item.team }}/.ipynb_checkpoints
    state: directory
    owner: root
    group: "{{ item.team }}"
    mode: "2775"

- name: White list the users
  become: true
  ansible.builtin.command:
    cmd: tljh-config add-item users.allowed {{ user }}
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user

- name: Add the users of the team to the group
  become: true
  ansible.builtin.user:
    name: jupyter-{{ user }}
    append: true # add users to groups and leave current groups alone
    groups: "{{ item.team }}"
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user

- name: Link shared folder into the users home directory
  become: true
  ansible.builtin.file:
    dest: /home/jupyter-{{ user }}/{{ item.team }}
    src: /srv/data/teams/{{ item.team }}
    owner: jupyter-{{ user }}
    group: jupyter-{{ user }}
    follow: false
    state: link
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user

- name: Ensure the symlink exists to the examples directory for every user
  become: true
  ansible.builtin.file:
    src: /opt/local/plex/python/notebooks
    dest: /home/jupyter-{{ user }}/examples
    follow: false
    state: link
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user
