- name: Pull commonly used containers
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - "ubuntu"
    - "alpine"
    - "nvidia/cuda"
    - "docker.io/library/python:3.9-slim"
    - "docker.io/rapidsai/mambaforge-cuda:cuda11.8.0-base-ubuntu22.04-py3.9"
    - "docker.io/pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime"
    - "ghcr.io/labdao/equibind:main@sha256:21a381d9ab1ff047565685044569c8536a55e489c9531326498b28d6b3cc244f"
    - "ghcr.io/labdao/equibind@sha256:ae2cec63b3924774727ed1c6c8af95cf4aaea2d3f0c5acbec56478505ccb2b07"
  async: 86400
  poll: 0
