---
Node:
    ServerAPI:
        Host: 0.0.0.0
        Port: 1234
        TLS:
            AutoCert: ""
            AutoCertCachePath: ""
            ServerCertificate: ""
            ServerTLSKey: ""
    Libp2P:
        SwarmPort: 1235
        PeerConnect: none
    IPFS:
        Connect: ""
        PrivateInternal: false
        SwarmKeyPath: ""
        ServePath: ""
    Compute:
        Capacity:
            IgnorePhysicalResourceLimits: false
            TotalResourceLimits:
                CPU: ""
                Memory: ""
                Disk: ""
                GPU: ""
            JobResourceLimits:
                CPU: ""
                Memory: ""
                Disk: ""
                GPU: ""
            DefaultJobResourceLimits:
                CPU: 500m
                Memory: 500Mi
                Disk: ""
                GPU: ""
            QueueResourceLimits:
                # 100x CPU
                CPU: "{{ ansible_processor_vcpus | int * 100 }}"
                # 100x memory
                Memory: "{{ ansible_memtotal_mb | int * 100 }}Mi"
                # 100x disk
                Disk: "100000Gb"
                # If GPU is available, set it to 100x to accept more jobs
                GPU: "{% if num_of_gpus | int > 0 %}{{ num_of_gpus | int * 100 }}{% endif %}"
            MaxJobExecutionTimeout: 0s
        ExecutionStore:
            Type: BoltDB
            Path: ""
        JobTimeouts:
            JobExecutionTimeoutClientIDBypassList: []
            JobNegotiationTimeout: 3m0s
            MinJobExecutionTimeout: 500ms
            MaxJobExecutionTimeout: {{ bacalhau_max_job_execution_timeout | default('24h') }}
            DefaultJobExecutionTimeout: 10m0s
        JobSelection:
            Locality: anywhere
            RejectStatelessJobs: false
            AcceptNetworkedJobs: true
            ProbeHTTP: "{{ receptor_url }}"
            ProbeExec: ""
        Queue:
            ExecutorBufferBackoffDuration: 50ms
        Logging:
            LogRunningExecutionsInterval: 10s
User:
    KeyPath: /home/ubuntu/.bacalhau/user_id.pem
    Libp2PKeyPath: /home/ubuntu/.bacalhau/libp2p_private_key
Metrics:
    Libp2PTracerPath: /dev/null
    EventTracerPath: /dev/null
