- name: Provision Canary
  remote_user: ubuntu
  hosts: "{{ target_hosts | default('tag_Type_compute_only') }}"
  vars:
    canary_dir: /opt/local/canary
    repo_dir: "{{ canary_dir }}/repo"
    binary_dir: "{{ canary_dir }}/binary"
  tasks:
    # Must provide limit flag to ensure running against current environment
    - fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

    - name: Ensure directories exist, writable by user
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu
        state: directory
      loop:
        - "{{ repo_dir }}"
        - "{{ binary_dir }}"

    - name: Pull the plex repository
      ansible.builtin.git:
        repo: https://github.com/labdao/plex.git
        dest: "{{ repo_dir }}/"

    - name: Install Plex
      ansible.builtin.include_tasks:
        file: tasks/install_plex_tasks.yaml
      vars:
        plex_dir: "{{ binary_dir }}"

    - name: Place equibind canary script
      ansible.builtin.template:
        src: files/equibind_canary.sh
        dest: "{{ canary_dir }}/equibind_canary.sh"
        mode: 'u+x'

    - name: Place colabfold canary script
      ansible.builtin.template:
        src: files/colabfold_mini_canary.sh
        dest: "{{ canary_dir }}/colabfold_mini_canary.sh"
        mode: 'u+x'

    - name: Set a cron job to run equibind canary
      ansible.builtin.cron:
        name: "Run equibind canary"
        job: "{{ canary_dir }}/equibind_canary.sh"
        minute: "*/5" # every 5 minutes

    - name: Set a cron job to run colabfold
      ansible.builtin.cron:
        name: "Run colabfold canary"
        job: "{{ canary_dir }}/colabfold_mini_canary.sh"
        minute: "27" # once per hour
