- name: Provision Requester
  remote_user: ubuntu
  hosts: tag_Type_requester
  vars:
    ipfs_path: /opt/local/ipfs
  tasks:
    # Aptitude is preferred by ansible
    - name: Install aptitude
      become: yes
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install IPFS
      ansible.builtin.get_url:
        url: https://dist.ipfs.tech/kubo/v0.18.0/kubo_v0.18.0_linux-amd64.tar.gz
        dest: /tmp/ipfs.tar.gz  
    
    - name: Make a folder to put IPFS files in
      ansible.builtin.file:
        path: /tmp/ipfs
        state: directory

    - name: Unzip IPFS
      become: yes
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/ipfs.tar.gz
        dest: /tmp/ipfs

    - name: Install Kubo
      become: yes
      ansible.builtin.command: /tmp/ipfs/kubo/install.sh

    - name: Create IPFS directory
      become: yes
      ansible.builtin.file:
        owner: ubuntu
        group: ubuntu
        path: /opt/local/ipfs
        state: directory

    - name: Put the IPFS directory in env for future shells
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: IPFS_PATH={{ ipfs_path }}

    - name: Initiazlie IPFS
      ansible.builtin.command:
        cmd: ipfs init
        creates: "{{ ipfs_path }}/config"

    - name: Configure IPFS
      ansible.builtin.shell: |
        ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
        ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
        ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "POST"]'
        ipfs config Pinning.Recursive true

    - name: Install the IPFS systemd unit
      become: yes
      ansible.builtin.copy:
        src: files/ipfs.service
        dest: /etc/systemd/system

    - name: Enable and start the IPFS Daemon
      become: yes
      ansible.builtin.service:
        name: ipfs
        state: started
        enabled: true

    - name: Install Bacalhau
      ansible.builtin.shell:
        cmd: curl -sL https://get.bacalhau.org/install.sh | bash

    - name: Bump System Resources
      become: yes
      ansible.builtin.command: sysctl -w net.core.rmem_max=2500000

    - name: Install the Bacalhau systemd unit
      become: yes
      ansible.builtin.template:
        src: files/requester.service
        dest: /etc/systemd/system
      vars:
        owner: labdao
        ipfs_connect: /ip4/127.0.0.1/tcp/5001
        receptor_url: http://ip-172-31-82-127.ec2.internal:8080/judge
      notify:
        - Restart Bacalhau

    - name: Systemd Daemon Reload
      become: yes
      ansible.builtin.systemd:
        daemon_reload: true

  handlers:
    - name: Restart Bacalhau
      become: yes
      ansible.builtin.service:
        name: requester
        state: restarted
        enabled: true
