- name: Provision Bacalhau Compute Instance
  remote_user: ubuntu
  hosts: tag_Type_compute_only
  vars:
    nvidia_distribution: ubuntu2004
    ipfs_version: "0.18.0"
    ipfs_path: "/opt/ipfs"
    gpu: true
    go_version: 1.20.3
    bacalhau_version: "v1.0.3"
    bacalhau_node_type: "compute"
    ipfs_connect: /ip4/127.0.0.1/tcp/5001
    owner: labdao
  tasks:
    # Must provide limit flag to ensure running against correct environment
    - fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    # Aptitude is preferred by ansible
    - name: Install aptitude and other required system packages
      become: yes
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - aptitude
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - tar
          - gzip
          - unzip
          - git

    # Docker
    - name: Install Docker
      ansible.builtin.include_tasks: tasks/install_docker_tasks.yaml

    # GPU
    - name: Install tools and binaries for GPU support
      ansible.builtin.include_tasks: tasks/install_gpu_tasks.yaml
      when: gpu

    # Ensure handlers are restarted before continuing
    - name: flush handlers
      ansible.builtin.meta: flush_handlers

    # Required docker since IPFS runs in container
    - name: Install IPFS
      ansible.builtin.include_tasks: tasks/install_ipfs_tasks.yaml
      tags: ipfs_install

    # Run Bacalhau agent
    - name: Run Baclahau container
      ansible.builtin.include_tasks: tasks/install_bacalhau_tasks.yaml
      tags: bacalhau

  handlers:
    - name: Restart docker
      become: yes
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Restart Bacalhau
      become: yes
      ansible.builtin.service:
        name: compute
        state: restarted
        enabled: true
