- name: Provision Canary
  remote_user: ubuntu
  hosts: "{{ target_hosts | default('tag_Type_compute') }}"
  vars:
    canary_dir: /opt/local/canary
    repo_dir: "{{ canary_dir }}/repo"
    binary_dir: "{{ canary_dir }}/binary"
  tasks:
    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

    - name: Ensure directories exist, writable by user
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        owner: ubuntu
        group: ubuntu
        state: directory
      loop:
        - "{{ repo_dir }}"
        - "{{ binary_dir }}"

    - name: Pull the plex repository
      ansible.builtin.git:
        repo: https://github.com/labdao/plex.git
        dest: "{{ repo_dir }}/"

    - name: Install Plex
      ansible.builtin.include_tasks:
        file: tasks/install_plex_tasks.yaml
      vars:
        plex_dir: "{{ binary_dir }}"

    - name: Place canary srcript
      ansible.builtin.template:
        src: files/equibind_canary.sh
        dest: "{{ canary_dir }}/equibind_canary.sh"
        mode: 'u+x'

    - name: Set a cron job to run canary
      ansible.builtin.cron:
        name: "Run equibind canary"
        job: "{{ canary_dir }}/equibind_canary.sh"
        minute: "*/5"
