- name: Provision Bacalhau Requester
  remote_user: ubuntu
  hosts: "{{ target_hosts | default('tag_Type_requester') }}"
  vars:
    ipfs_version: "0.18.0"
    ipfs_path: "/opt/ipfs"
    bacalhau_version: "v1.2.0"
    bacalhau_node_type: "requester"
    ipfs_connect: /ip4/127.0.0.1/tcp/5001
    owner: labdao
  tasks:
    # Must provide limit flag to ensure running against current environment
    - fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

          # - name: Install IPFS
          #   ansible.builtin.include_tasks: tasks/install_ipfs_tasks.yaml

    # Run Bacalhau agent
    - name: Install Bacalhau
      ansible.builtin.include_tasks: tasks/install_bacalhau_tasks.yaml
      tags: bacalhau

    - name: Systemd Daemon Reload
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

  handlers:
    - name: Restart Bacalhau
      become: true
      ansible.builtin.service:
        name: requester
        state: restarted
        enabled: true
