- name: Provision Bacalhau Compute Instance
  remote_user: ubuntu
  # Ability to override host, useful to running playbook in local mode
  hosts: "all"
  gather_facts: true
  vars:
    go_version: 1.20.3
    owner: labdao
  tasks:
    # Must provide limit flag to ensure running against correct environment
    # - name: Checking if limit is provided
    #   ansible.builtin.fail:
    #     msg: "you must use -l or --limit"
    #   when: ansible_limit is not defined
    #   run_once: true

    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

    # Get GPU info from system
    - name: Get lshw display info
      become: true
      ansible.builtin.command: lshw -c display -json
      changed_when: true
      register: lshw_output

    - name: set number of gpus available
      vars:
        query: "[?vendor=='NVIDIA Corporation']"
      ansible.builtin.set_fact:
        num_of_gpus: "{{ lshw_output.stdout | from_json | json_query(query) | length }}"

    # Docker
    # Run it after number of GPUs have been determined on the node
    - name: Install Docker
      ansible.builtin.include_tasks: tasks/install_docker_tasks.yaml

    # GPU
    - name: Install tools and binaries for GPU support
      ansible.builtin.include_tasks: tasks/install_gpu_tasks.yaml
      when: num_of_gpus | int > 0 or (force_gpu_install is defined and force_gpu_install | bool)

    # Tailscale
    - name: Install tailscale
      ansible.builtin.include_tasks: tasks/install_tailscale_tasks.yaml

    # Ensure handlers are restarted before continuing
    - name: flush handlers
      ansible.builtin.meta: flush_handlers

  handlers:
    - name: Reload systemd
      become: true
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart docker
      become: true
      ansible.builtin.service:
        name: docker
        state: restarted
