- name: Provision IPFS
  remote_user: ubuntu
  hosts: "{{ target_hosts | default('tag_Type_ipfs') }}"
  vars:
    ipfs_version: "0.18.0"
    ipfs_path: "/opt/ipfs"
    ipfs_connect: /ip4/127.0.0.1/tcp/5001
  tasks:
    # Must provide limit flag to ensure running against current environment
    - fail:
        msg: "you must use -l or --limit"
      when: ansible_limit is not defined
      run_once: true

    - name: Run common tasks
      ansible.builtin.include_tasks: tasks/common_tasks.yaml

    # Docker
    - name: Install Docker
      ansible.builtin.include_tasks: tasks/install_docker_tasks.yaml

    - name: Install IPFS
      ansible.builtin.include_tasks: tasks/install_ipfs_docker_tasks.yaml

    - name: Systemd Daemon Reload
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

  handlers:
    - name: Restart IPFS
      become: true
      ansible.builtin.service:
        name: ipfs
        state: restarted
        enabled: true
