- name: Provisition Plex
  remote_user: ubuntu
  hosts: tag_Type_jupyter_notebook
  vars_files:
    - vars/teams.yaml
  tasks:
    - name: Create admin users
      become: yes
      ansible.builtin.command:
        cmd: tljh-config add-item users.admin {{ item }}
      loop: "{{ admins }}"

    - name: Create shared folder for teams
      become: yes
      ansible.builtin.file:
        path: /srv/data/teams
        state: directory
        
    - name: Create teams
      include_tasks: jupyter_team_setup_tasks.yaml
      loop: "{{ teams }}"

    - name: Reload the tljh configuration
      become: yes
      ansible.builtin.command: tljh-config reload
