basic_settings:
  experiment_name: large
  binder_length: 100
  pdb: /inputs/target_protein.pdb
  pdb_chain: D
  num_designs: 32
advanced_settings:
  pdb_start_residue: 50
  pdb_end_residue: 200
  hotspot: 'D170,D171,D172,D173,D174,D76,D161'
  min_binder_length: null
  max_binder_length: null
  use_beta_model: false
expert_settings:
  RFDiffusion_Binder:
    contigs_override: ''
    # the contigs_override completely overrules all other contig related settings. Make sure it is '' if you do not want to overwrite settings.
    iterations: 50
    visual: none
  RFDiffusion_Symmetry:
    symmetry: none
    order: 1
    chains: ''
    add_potential: true
  ProteinMPNN:
    num_seqs: 32
    rm_aa: C
    mpnn_sampling_temp: 0.1
    use_solubleMPNN: true
    initial_guess: true
  Alphafold:
    use_multimer: false
    num_recycles: 3
