basic_settings:
  experiment_name: default
  binder_length: 50
  pdb: /inputs/target_protein.pdb
  pdb_chain: A
  num_designs: 2
expert_settings:
  ProteinMPNN:
    num_seqs: 8
    rm_aa: C
    mpnn_sampling_temp: 0.1
    use_solubleMPNN: true
    initial_guess: true
