basic_settings:
  experiment_name: default
  AF2_repeats_per_seq: 1
  number_of_evo_cycles: 45
  policy_flag: policy_sampling
  target_seq: TLGAVQIMNGLFHIALGSLLMIHTDVCAPICITMWYPLWGGIMFIISGSLLAAADKNPRKSLVKGKMIMNSLSLFAAISGIIFLIMDIFNITISHFFKMENLNLIKAPMPYVDIHNCDPANPSEKNSLSIQYCGSIRSVFLGVFAVMLIF
  init_permissibility_vec: '++++++++++++++++++++++++++FWDKAMGWXXQAPGKEREFVAGIGW----NTNYADSVKGRFTISRDNAKNTVYXXXNSLKPEDTAVYYCAVLDNYLYYYEDSLWYNFIYWGQGTQVTV--'
  temperature: 100.
  max_levenshtein_step_size: 4
  alphabet: 'LAGVSERTIDPKQNFYMHWC'
  # max_number_of_offspring_kept: 1
  # k: 1
  # number of AF2 repeats
  # consider adding the dictionary which relates actions and code
  # consider adding the set of non-tirival actions
  # add start and end resiude