basic_settings:
  experiment_name: default
  number_of_evo_cycles: 2
  policy_flag: policy_sampling
  init_permissibility_vec: 'B1:5/x6:11/+12:17'
  temperature: 2.
  max_levenshtein_step_size: 10
  alphabet: 'LAGVSERTIDPKQNFYMHWC'
  scorers: 'Hamming'
  scoring_metrics: 'hamming_distance'
  scoring_weights: '0.7,0.2,0.1'
  bouncer_flag: 'boltzmann'
  generators: 'random_flips'
  target_template_complex: '/app/protein_complex.pdb'
  target_chain: A
  binder_chain: B
  target_seq: ''
  binder_template_sequence: ''