basic_settings:
  experiment_name: whos-the-weakest-link
  AF2_repeats_per_seq: 1
  number_of_evo_cycles: 2
  policy_flag: policy_sampling
  max_number_of_offspring_kept: 1
  target_seq: TLGAVQIMNGLFHIALGSLLMIHTDVCAPICITMWYPLWGGIMFIISGSLLAAADKNPRKSLVKGKMIMNSLSLFAAISGIIFLIMDIFNITISHFFKMENLNLIKAPMPYVDIHNCDPANPSEKNSLSIQYCGSIRSVFLGVFAVMLIF
  init_permissibility_vec: 'TLGXVQ++++LFHIAL'
  k: 1
  temperature: 100.
  max_levenshtein_step_size: 3
  alphabet: 'LAGVSERTIDPKQNFYMHWC'
  # consider adding the dictionary which relates actions and code
  # consider adding the set of non-tirival actions