basic_settings:
  experiment_name: default
  binder_length: 50
  pdb_chain: B
  num_designs: 2
advanced_settings:
  pdb_start_residue: 50
  pdb_end_residue: 200
  hotspot: ''
  min_binder_length: null
  max_binder_length: null
  use_beta_model: false
expert_settings:
  RFDiffusion_Binder:
    contigs_override: A1-283:27/7/B35-47/B48-60/B61-72/6/B79-99/7/B107-134/4/B139-162/B163-168/16/5/B190-225/B226-232/B233-244
    iterations: 50
    visual: none
  RFDiffusion_Symmetry:
    symmetry: none
    order: 1
    chains: ''
    add_potential: true
  ProteinMPNN:
    num_seqs: 8
    rm_aa: C
    mpnn_sampling_temp: 0.1
    use_solubleMPNN: true
    initial_guess: true
  Alphafold:
    use_multimer: false
    num_recycles: 3
