apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: dbdata-backend
  name: dbdata-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
