apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: default-tool-setup
  name: default-tool-setup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: default-tool-setup
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/plex-default: "true"
        io.kompose.service: default-tool-setup
    spec:
      containers:
        - args:
            - sh
            - -exc
            - ' apk add --no-cache curl jq && jq ''{"toolJson": ., "walletAddress": "0xA5B68dbA49cE48d0c1e0f29EA45885b5f83A0BD4"}'' /opt/plex/tools/colabdesign/colabdesign-gateway.json | curl -s -H "Content-Type: application/json" -X POST --data-binary @- http://backend:8080/tools && jq ''{"toolJson": ., "walletAddress": "0xA5B68dbA49cE48d0c1e0f29EA45885b5f83A0BD4"}'' /opt/plex/tools/labsay/labsay.json | curl -s -H "Content-Type: application/json" -X POST --data-binary @- http://backend:8080/tools && sleep infinity'
          image: alpine
          name: default-tool-setup
          volumeMounts:
            - mountPath: /opt/plex
              name: default-tool-setup-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: default-tool-setup-claim0
          persistentVolumeClaim:
            claimName: default-tool-setup-claim0
            readOnly: true
