apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: default-tool-setup-claim0
  name: default-tool-setup-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
