# Workflow to build backend/gateway container
---

name: backend

on:
  push:
    branches: ["main"]
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths-ignore:
      - 'docs/**'
      - 'infrastructure/**'

  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'infrastructure/**'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    uses: ./.github/workflows/docker.yml
    with:
      name: backend
    secrets: inherit
