name: Canary Run Equibind Tool

on:
  workflow_dispatch:
  schedule:
    - cron: '23 * * * *'

jobs:
  canary:
    runs-on: ubuntu-20.04
    environment: ci
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # Checkout the repository. Note we do not use anything other than the test data and tools directory
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the latest release
        run: |
          # use the GitHub CLI to download the latest release
          gh release download --repo labdao/plex --pattern "*linux_amd64.tar.gz"
          # extract the package
          tar -xf *.tar.gz

      - name: Run Equibind
        run: |
          # use tee so we can see stdout in github, and parse it later
          plex create -t {{ repo_dir }}/tools/equibind.json -i {{ repo_dir }}/testdata/binding/pdbbind_processed_size1 --autoRun=true 2>&1 | tee plex_out.log
          # capture the exit status of the plex call
          plex_result_code=${PIPESTATUS[0]}
          # exit immediately if plex exited with an error
          if [ $plex_result_code -gt 0 ]; then
            exit $plex_result_code
          fi
          # parse the output directory from the plex stdout
          result_dir=$(cat plex_out.log | grep 'Finished processing, results written to' | sed -n 's/^.*Finished processing, results written to //p' | sed 's/\/io.json//')
          # exit if no docked files are found
          cd "$result_dir/entry-0/outputs"
          if [ "$(find . -name '*docked.sdf' | grep 'docked.sdf')" == "" ]; then
            echo "No docked files found"
            exit 1
          else
            echo "Docked files found"
          fi
        env:
          PLEX_ACCESS_TOKEN: ${{ secrets.PLEX_ACCESS_TOKEN }}

      - name: Check in with Heii On-Call
        run: |
          curl -X POST -H 'Authorization: Bearer ${{ secrets.HEII_ON_CALL_API_KEY }}' https://api.heiioncall.com./triggers/${HEII_ON_CALL_INBOUND_TRIGGER_ID}/checkin
        env:
          HEII_ON_CALL_INBOUND_TRIGGER_ID: df86b926-d9c1-4584-8c91-28ffde7af8c2
