name: Canary Run Equibind Tool

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'ops/**'
  # schedule:
  #  - cron: '*/10 * * * *'

jobs:
  canary:
    runs-on: ubuntu-20.04
    environment: releaser
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: Download the latest release
        run: |
          # echo $(gh release --repo labdao/plex list | grep Latest | cut -f1)
          # use the GitHub CLI to download the latest release
          gh release download --repo labdao/plex --pattern "*linux_amd64.tar.gz"
          # extract the package
          tar -xf *.tar.gz

      - name: Run Equibind
        run: |
          result_dir=$(./plex -tool equibind -input-dir testdata/binding/abl | grep 'Finished processing, results written to' | sed -n 's/^.*Finished processing, results written to //p' | sed 's/\/io.json//')
          cd "$result_dir/entry-0/outputs"
          if [ "$(find . -name '*docked.sdf' | grep 'docked.sdf')" == "" ]; then
            echo "No docked files found"
            exit 1
          else
            echo "Docked files found:"
            find . -name '*docked.sdf' | grep 'docked.sdf'
          fi
        env:
          PLEX_ACCESS_TOKEN: ${{ secrets.PLEX_ACCESS_TOKEN }}
