name: Canary Run Equibind Tool

on:
  workflow_dispatch: {}
  # schedule:
  #  - cron: '*/10 * * * *'

jobs:
  canary:
    runs-on: ubuntu-20.04
    environment: releaser
    steps:

      - name: Download the latest release
        run: |
          latest_release=$(gh list releases | cut -f1)
          echo latest_relase

      # - name: Run Equibind
      #   run: |
      #     result_dir=$(./plex -tool equibind -input-dir testdata/binding/abl | grep 'Finished processing, results written to' | sed -n 's/^.*Finished processing, results written to //p' | sed 's/\/io.json//')
      #     cd "$result_dir/entry-0/outputs"
      #     if [ "$(find . -name '*docked.sdf' | grep 'docked.sdf')" == "" ]; then
      #       echo "No docked files found"
      #       exit 1
      #     else
      #       echo "Docked files found:"
      #       find . -name '*docked.sdf' | grep 'docked.sdf'
      #     fi
      #   env:
      #     PLEX_ACCESS_TOKEN: ${{ secrets.PLEX_ACCESS_TOKEN }}
