# This workflow is for plex jobs against locally running environment

name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'infrastructure/**'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'infrastructure/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-22.04
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Commands
        run: |
          # Install docker-compose
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker version
          docker compose version
          docker run ubuntu echo hello world
