---

# This workflow will deploy containers onto specific environments

name: deploy

on:
  workflow_run:
    workflows:
      - "CI"
      - "frontend"
      - "backend" 
    # branches: [main]
    types: 
      - completed

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
