# Workflow to build frontend container
---

name: frontend

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/**'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      matrix:
        backends: [{ env: stg, url: 'https://api.stg.labdao.xyz'}, { env: prod, url: 'https://api.prod.labdao.xyz'}, { env: local, url: 'http://localhost:8080'}]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Base ref
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then BASEREF="${{ github.event.base_ref }}"; BASEREF="${BASEREF#refs/heads/}"; elif [ "${{ github.ref_type }}" = "branch" ]; then BASEREF="${{ github.ref_name }}"; else BASEREF=""; fi
          echo "BASEREF=${BASEREF}" >> $GITHUB_ENV

          # - if: github.ref == 'refs/heads/main'
          #   name: Conditional(Set tag as `latest`)
          #   run: echo "tag=latest" >> $GITHUB_ENV

          # - if: startsWith(github.ref, 'refs/tags/')
          #   name: Conditional(Set tag as `{version}`)
          #   run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.LABDAO_QUAY_USERNAME }}
          password: ${{ secrets.LABDAO_QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ matrix.backends.url }}
          push: true
          tags: quay.io/labdao/frontend:${{ env.BASEREF }}-${{ matrix.backends.env }}
