# Workflow to build frontend container
---

name: frontend

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'frontend/**'
      - '.github/**'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      matrix:
        backends: [{ env: stg, url: 'https://api.stg.labdao.xyz'}, { env: prod, url: 'https://api.prod.labdao.xyz'}, { env: local, url: 'http://localhost:8080'}]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/labdao/frontend
          tags: |
            type=ref,suffix=-${{ matrix.backends.env }},event=branch
            type=ref,suffix=-${{ matrix.backends.env }},event=pr
            type=ref,suffix=-${{ matrix.backends.env }},event=tag
  
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.LABDAO_QUAY_USERNAME }}
          password: ${{ secrets.LABDAO_QUAY_PASSWORD }}

      - name: Build and push
        env:
          NEXT_PUBLIC_PRIVY_APP_ID: ${{ secrets.NEXT_PUBLIC_PRIVY_APP_ID }}
        uses: docker/build-push-action@v5
        with:
          build-args: |
            NEXT_PUBLIC_BACKEND_URL=${{ matrix.backends.url }}
            NEXT_PUBLIC_PRIVY_APP_ID
          push: true
          context: frontend/
          tags: ${{ steps.meta.outputs.tags }}
