# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Install dependencies
      run: go mod download

    - name: Tidy dependencies
      run: go mod tidy

    - name: Build
      run: go build

    - name: Test
      env:
          WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}
          IPFS_NODE_URL: ${{ secrets.IPFS_NODE_URL }}
      run: go test ./... -v

    - name: Run Colabfold
    run: |
      cd "$(./plex -app colabfold-min -input-dir testdata/folding | sed -n 's/^Your job results have been downloaded to //p')"
      cd combined_results/outputs
      if [ "$(find . -name '*.pdb' | grep '.pdb')" == "" ]; then
        echo "No results found"
        exit 1
      else
        echo "results found:"
        find . -name '*.pdb' | grep '.pdb'
      fi
