# Workflow to build ipfs container
---

name: ipfs

on:
  push:
    branches: ["main"]
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths:
      - 'docker/images/ipfs/**'
      - '.github/workflows/ipfs.yml'

  pull_request:
    branches: ["main"]
    paths:
      - 'docker/images/ipfs/**'
      - '.github/workflows/ipfs.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    uses: ./.github/workflows/docker.yml
    with:
      name: ipfs
      context: docker/images/ipfs
    secrets: inherit
