# Workflow to build ipfs container
---

name: ipfs

on:
  push:
    branches: ["main"]
    paths:
      - 'docker/images/ipfs/**'
      - '.github/workflows/ipfs.yml'

  pull_request:
    branches: ["main"]
    paths:
      - 'docker/images/ipfs/**'
      - '.github/workflows/ipfs.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/labdao/ipfs
  
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.LABDAO_QUAY_USERNAME }}
          password: ${{ secrets.LABDAO_QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: |
            quay.io/labdao/ipfs:main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
