name: Test Pre-releases

on:
  push:
    tags:
      - '*-alpha'

# TODO: expand for other OS/ARCH (see go-ipfs-api matrix)
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Get tag name
        id: tag_name
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Download pre-release files
        run: |
          curl -sSL https://github.com/labdao/plex/releases/download/${{ steps.tag_name.outputs.tag }}/plex_${{ steps.tag_name.outputs.tag }}_linux_amd64.tar.gz

      - name: Extract pre-release files
        run: |
          tar xvz plex_${{ steps.tag_name.outputs.tag }}_linux_amd64.tar.gz
          
      - name: Test equibind
        run: |
          ./plex -app equibind -input-dir ./testdata/binding/pdbbind_processed_size1/

      # TODO: 
      # 1) determine output file directory (should be in logs of previous step)
      # 2) cd into subdirectory with output files
      # 3) read the files for expected format
      
      
