# Workflow to build receptor container
---

name: receptor

on:
  push:
    branches: ["main"]
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths:
      - 'receptor/**'
      - '.github/workflows/receptor.yml'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'receptor/**'
      - '.github/workflows/receptor.yml'
      - '.github/workflows/docker.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  receptor:
    uses: ./.github/workflows/docker.yml
    with:
      name: receptor
      context: receptor
    secrets: inherit
