# Workflow to tools containers
---

name: tools

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "staging"
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'
      - '.github/workflows/docker.yml'

  pull_request:
    branches:
      - "main"
      - "staging"
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'
      - '.github/workflows/docker.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ################ TOOLS CONTAINER BUILDS ###########################
  changes-tools:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      tools: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Only run when tool's directory or workflow files have changed
        ###############################################################
        ################## Add new tools here #########################
        ###############################################################
        filters: |
          colabdesign:
            - 'tools/colabdesign/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          colabdesign-checkpoint:
            - 'tools/colabdesign-checkpoint/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          labsay-checkpoint:
            - 'tools/labsay-checkpoint/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          colabdesign-autoprompt:
            - 'tools/colabdesign-autoprompt/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          rf-diffusion:
            - 'tools/rf-diffusion/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          protein-mpnn:
            - 'tools/protein-mpnn/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          generator:
            - 'tools/generator/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          protein-to-dna-icodon:
            - 'tools/protein-to-dna-icodon/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'
          af2:
            - 'tools/af2/**'
            - '.github/workflows/tools.yml'
            - '.github/workflows/docker.yml'


  tools:
    needs: changes-tools
    if: ${{ needs.changes-tools.outputs.tools != '' && toJson(fromJson(needs.changes-tools.outputs.tools)) != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        tools: "${{ fromJSON(needs.changes-tools.outputs.tools) }}"
    uses: ./.github/workflows/docker.yml
    with:
      name: ${{ matrix.tools }}
      context: tools/${{ matrix.tools }}
      run-disk-space-cleanup: true
    secrets: inherit
