# Workflow to build tools containers
---

name: tools

on:
  push:
    branches: ["main"]
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tools:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tools:
          - colabdesign
          - colabfold
          - oddt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: .github/scripts/free-disk-space.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/labdao/${{matrix.tools}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
  
      - name: Login to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.LABDAO_QUAY_USERNAME }}
          password: ${{ secrets.LABDAO_QUAY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          cache-from: |
            quay.io/labdao/${{matrix.tools}}:main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          context: tools/${{matrix.tools}}
