# Workflow to build tools containers
---

name: tools

on:
  push:
    branches: ["main"]
    # Pattern matched against refs/tags
    tags:
      - '**'
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'tools/**'
      - '.github/workflows/tools.yml'

# Only run one at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tools:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tools:
          - colabdesign
          - colabfold
          - oddt
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use docker reuseable workflow
        uses: ./.github/workflows/docker.yml
        with:
          name: ${{matrix.tools}}
          context: tools/${{matrix.tools}}
